spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA  APIs testing"
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "{cipher}fd051c396df85693a76d4af715f177170da04b83faa03243da9b618ae4f40809d952b0113270c48b90e46aeb7a9a96bf"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371
