spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related prod APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "{cipher}e1d3967216b6c657db1a63195e7a679732a7f3b27c418e686a998366d6929cf3b929ef13b134fcc67dd9e0b2b6bb7ab4"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
