spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related Quality Assurance APIs "
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "cherryl@eazybank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267
